---

- name: install php
  apt: pkg={{item}} update_cache=no state=latest
  with_items:
    - php5
    - php5-dev
    - php5-fpm
    - php5-mongo
    - php5-mysql
    - php5-json
    - php5-gd
    - php5-curl
    - php5-xdebug
  notify:
    - restart php5-fpm

- name: set the automatic start-up of the php5-fpm
  command: sysv-rc-conf php5-fpm on

- name: template /etc/php5/fpm/php.ini
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini group=root owner=root mode=0644
  notify:
    - restart php5-fpm

- name: template /etc/php5/fpm/pool.d/www.conf
  template: src=www.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf group=root owner=root mode=0644
  notify:
    - restart php5-fpm