---

- name: template /etc/nginx/sites-available/default
  template: src=default.j2 dest=/etc/nginx/sites-available/default group=root owner=root mode=0644
  notify:
    # handlersの名前
    - restart nginx